<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"pt-BR\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Login e Cadastro</title>\n";
echo "    <style>\n";
echo "        body {\n";
echo "            background-color: #f1f1f1;\n";
echo "            background-position: center;\n";
echo "            background-repeat: no-repeat;\n";
echo "            background-size: cover;\n";
echo "            margin: 0;\n";
echo "            padding-top: 60px;\n";
echo "            font-family: Arial, sans-serif;\n";
echo "            background-color: #ffffff;\n";
echo "        }\n";
echo "        \n";
echo "        .top-bar {\n";
echo "            background-color: #00008b;\n";
echo "            color: white;\n";
echo "            position: fixed;\n";
echo "            top: 0;\n";
echo "            width: 100%;\n";
echo "            padding: 10px;\n";
echo "            box-shadow: 0 0 10px rgba(199, 199, 200, 0.905);\n";
echo "            display: flex;\n";
echo "            justify-content: space-between;\n";
echo "            align-items: center;\n";
echo "        }\n";
echo "        \n";
echo "        .top-bar .user-info {\n";
echo "            margin-left: 20px;\n";
echo "        }\n";
echo "        \n";
echo "        .top-bar .logout-btn {\n";
echo "            margin-right: 20px;\n";
echo "            background-color: #ff4d4d;\n";
echo "            border: none;\n";
echo "            color: white;\n";
echo "            padding: 10px;\n";
echo "            border-radius: 5px;\n";
echo "            cursor: pointer;\n";
echo "            transition: background-color 0.3s;\n";
echo "        }\n";
echo "        \n";
echo "        .top-bar .logout-btn:hover {\n";
echo "            background-color: #d93636;\n";
echo "        }\n";
echo "        \n";
echo "        .container {\n";
echo "            background-color: #ffffff;\n";
echo "            border-radius: 10px;\n";
echo "            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);\n";
echo "            width: 400px;\n";
echo "            max-width: 100%;\n";
echo "            padding: 20px;\n";
echo "            margin: 20px auto;\n";
echo "            position: relative;\n";
echo "            overflow: hidden;\n";
echo "        }\n";
echo "        \n";
echo "        .container::before {\n";
echo "            content: \'\';\n";
echo "            position: absolute;\n";
echo "            top: 0;\n";
echo "            left: 0;\n";
echo "            width: 100%;\n";
echo "            height: 100%;\n";
echo "            background: linear-gradient(45deg, rgba(0, 123, 255, 0.7), rgba(0, 123, 255, 0.1));\n";
echo "            z-index: -1;\n";
echo "            transition: opacity 0.5s;\n";
echo "            opacity: 0.5;\n";
echo "            animation: lightGlow 5s infinite alternate;\n";
echo "        }\n";
echo "        \n";
echo "        @keyframes lightGlow {\n";
echo "            0% {\n";
echo "                opacity: 0.5;\n";
echo "            }\n";
echo "            100% {\n";
echo "                opacity: 0.8;\n";
echo "            }\n";
echo "        }\n";
echo "        \n";
echo "        img {\n";
echo "            display: block;\n";
echo "            margin: 0 auto 20px;\n";
echo "            max-width: 100px;\n";
echo "            animation: fadeIn 1s ease-in-out;\n";
echo "        }\n";
echo "        \n";
echo "        h2 {\n";
echo "            text-align: center;\n";
echo "            color: #00008b;\n";
echo "            animation: fadeIn 1s ease-in-out;\n";
echo "        }\n";
echo "        \n";
echo "        .form-group {\n";
echo "            margin-bottom: 15px;\n";
echo "            position: relative;\n";
echo "        }\n";
echo "        \n";
echo "        .form-group label {\n";
echo "            display: block;\n";
echo "            color: #333;\n";
echo "            animation: fadeIn 1.2s ease-in-out;\n";
echo "        }\n";
echo "        \n";
echo "        .form-group input,\n";
echo "        .form-group textarea,\n";
echo "        .form-group select {\n";
echo "            width: calc(100% - 20px);\n";
echo "            padding: 10px;\n";
echo "            border: 1px solid #ddd;\n";
echo "            border-radius: 5px;\n";
echo "            margin-top: 5px;\n";
echo "            transition: border-color 0.3s;\n";
echo "            animation: fadeIn 1.4s ease-in-out;\n";
echo "        }\n";
echo "        \n";
echo "        .form-group input:focus,\n";
echo "        .form-group textarea:focus,\n";
echo "        .form-group select:focus {\n";
echo "            border-color: #007bff;\n";
echo "            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);\n";
echo "        }\n";
echo "        \n";
echo "        .form-group button,\n";
echo "        .main-btn {\n";
echo "            width: 100%;\n";
echo "            padding: 10px;\n";
echo "            background-color: #00008b;\n";
echo "            color: #fff;\n";
echo "            border: none;\n";
echo "            border-radius: 5px;\n";
echo "            cursor: pointer;\n";
echo "            font-size: 16px;\n";
echo "            transition: background-color 0.3s, transform 0.3s;\n";
echo "            animation: fadeIn 1.6s ease-in-out;\n";
echo "            margin-top: 10px;\n";
echo "        }\n";
echo "        \n";
echo "        .form-group button:hover,\n";
echo "        .main-btn:hover {\n";
echo "            background-color: #0056b3;\n";
echo "            transform: scale(1.05);\n";
echo "        }\n";
echo "        \n";
echo "        .switch-form {\n";
echo "            text-align: center;\n";
echo "            margin-top: 20px;\n";
echo "            animation: fadeIn 1.8s ease-in-out;\n";
echo "        }\n";
echo "        \n";
echo "        .switch-form a {\n";
echo "            color: #007bff;\n";
echo "            text-decoration: none;\n";
echo "        }\n";
echo "        \n";
echo "        .switch-form a:hover {\n";
echo "            text-decoration: underline;\n";
echo "        }\n";
echo "        \n";
echo "        @keyframes fadeIn {\n";
echo "            from {\n";
echo "                opacity: 0;\n";
echo "            }\n";
echo "            to {\n";
echo "                opacity: 1;\n";
echo "            }\n";
echo "        }\n";
echo "        \n";
echo "        .loader-overlay {\n";
echo "            position: fixed;\n";
echo "            top: 0;\n";
echo "            left: 0;\n";
echo "            width: 100%;\n";
echo "            height: 100%;\n";
echo "            background: rgba(255, 255, 255, 0.8);\n";
echo "            display: flex;\n";
echo "            justify-content: center;\n";
echo "            align-items: center;\n";
echo "            z-index: 1000;\n";
echo "            display: none;\n";
echo "        }\n";
echo "        \n";
echo "        .loader {\n";
echo "            width: 50px;\n";
echo "            height: 50px;\n";
echo "            border: 5px solid rgba(0, 123, 255, 0.2);\n";
echo "            border-top: 5px solid #007bff;\n";
echo "            border-radius: 50%;\n";
echo "            animation: spin 1s linear infinite;\n";
echo "        }\n";
echo "        \n";
echo "        @keyframes spin {\n";
echo "            0% {\n";
echo "                transform: rotate(0deg);\n";
echo "            }\n";
echo "            100% {\n";
echo "                transform: rotate(360deg);\n";
echo "            }\n";
echo "        }\n";
echo "        \n";
echo "        #success-container {\n";
echo "            display: none;\n";
echo "            flex-direction: column;\n";
echo "            align-items: center;\n";
echo "        }\n";
echo "        \n";
echo "        .main-container {\n";
echo "            display: none;\n";
echo "            flex-direction: column;\n";
echo "            align-items: center;\n";
echo "        }\n";
echo "        \n";
echo "        #success-form,\n";
echo "        #user-data,\n";
echo "        #filter-data {\n";
echo "            display: none;\n";
echo "            flex-direction: column;\n";
echo "        }\n";
echo "        \n";
echo "        #user-data table {\n";
echo "            width: 100%;\n";
echo "            border-collapse: collapse;\n";
echo "        }\n";
echo "        \n";
echo "        #user-data th,\n";
echo "        #user-data td {\n";
echo "            padding: 10px;\n";
echo "            border: 1px solid #ddd;\n";
echo "        }\n";
echo "        \n";
echo "        .captcha-container {\n";
echo "            display: flex;\n";
echo "            align-items: center;\n";
echo "            margin-top: 10px;\n";
echo "        }\n";
echo "        \n";
echo "        .captcha-container input[type=\"checkbox\"] {\n";
echo "            margin-right: 10px;\n";
echo "        }\n";
echo "        \n";
echo "        .filter-group {\n";
echo "            margin-bottom: 15px;\n";
echo "        }\n";
echo "        /* New Styles for Tab Layout */\n";
echo "        \n";
echo "        .tab {\n";
echo "            overflow: hidden;\n";
echo "            background-color: #f1f1f1;\n";
echo "            border-bottom: 1px solid #ccc;\n";
echo "            display: flex;\n";
echo "            justify-content: space-around;\n";
echo "        }\n";
echo "        \n";
echo "        .tab button {\n";
echo "            background-color: inherit;\n";
echo "            border: none;\n";
echo "            outline: none;\n";
echo "            cursor: pointer;\n";
echo "            padding: 14px 16px;\n";
echo "            transition: 0.3s;\n";
echo "        }\n";
echo "        \n";
echo "        .tab button:hover {\n";
echo "            background-color: #ddd;\n";
echo "        }\n";
echo "        \n";
echo "        .tab button.active {\n";
echo "            background-color: #ccc;\n";
echo "        }\n";
echo "        \n";
echo "        .tabcontent {\n";
echo "            display: none;\n";
echo "            padding: 6px 12px;\n";
echo "            border-top: none;\n";
echo "        }\n";
echo "    </style>\n";
echo "</head>\n";
echo "<body>\n";
echo "    <div class=\"top-bar\">\n";
echo "        <div class=\"user-info\">\n";
echo "            <span id=\"user-name\"></span> | <span id=\"current-datetime\"></span>\n";
echo "        </div>\n";
echo "        <button class=\"logout-btn\" onclick=\"logout()\">Sair</button>\n";
echo "    </div>\n";
echo "    <div class=\"tab\">\n";
echo "        <button class=\"tablinks\" onclick=\"openTab(event, \'LoginCadastro\')\">Login/Cadastro</button>\n";
echo "        <button class=\"tablinks\" onclick=\"openTab(event, \'ResetarUsuario\')\">Resetar Usuário</button>\n";
echo "        <button class=\"tablinks\" onclick=\"openTab(event, \'RedesSociais\')\">Redes Sociais</button>\n";
echo "        <button class=\"tablinks\" onclick=\"openTab(event, \'Surpresa\')\">Surpresa</button>\n";
echo "    </div>\n";
echo "    <div id=\"LoginCadastro\" class=\"tabcontent\">\n";
echo "        <div class=\"container\" id=\"login-form\">\n";
echo "            <img src=\"c:\\Users\\Admin\\OneDrive\\Documentos\\Login\\nome_sistema.jpg\" alt=\"Logo\">\n";
echo "            <h2>Login</h2>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"login-email\">Login</label>\n";
echo "                <input type=\"text\" id=\"login-email\" name=\"login-email\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"login-password\">Senha</label>\n";
echo "                <input type=\"password\" id=\"login-password\" name=\"login-password\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <button type=\"button\" onclick=\"login()\">Entrar</button>\n";
echo "            </div>\n";
echo "            <div class=\"switch-form\">\n";
echo "                <span>Não tem uma conta? <a href=\"#\" onclick=\"toggleForms()\">Cadastre-se</a></span>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <div class=\"container\" id=\"signup-form\" style=\"display: none;\">\n";
echo "            <img src=\"c:\\Users\\Admin\\OneDrive\\Documentos\\Login\\nome_sistema.jpg\" alt=\"Logo\">\n";
echo "            <h2>Cadastro</h2>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"signup-name\">Nome</label>\n";
echo "                <input type=\"text\" id=\"signup-name\" name=\"signup-name\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"signup-email\">Email</label>\n";
echo "                <input type=\"email\" id=\"signup-email\" name=\"signup-email\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"signup-password\">Senha</label>\n";
echo "                <input type=\"password\" id=\"signup-password\" name=\"signup-password\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <button type=\"submit\" onclick=\"showLoader()\">Cadastrar</button>\n";
echo "            </div>\n";
echo "            <div class=\"switch-form\">\n";
echo "                <span>Já tem uma conta? <a href=\"#\" onclick=\"toggleForms()\">Entre</a></span>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div id=\"ResetarUsuario\" class=\"tabcontent\">\n";
echo "        <div class=\"container\">\n";
echo "            <h2>Resetar Usuário</h2>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"reset-email\">Email</label>\n";
echo "                <input type=\"email\" id=\"reset-email\" name=\"reset-email\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <button type=\"button\" onclick=\"resetUser()\">Resetar</button>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div id=\"RedesSociais\" class=\"tabcontent\">\n";
echo "        <div class=\"container\">\n";
echo "            <h2>Redes Sociais</h2>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"social-email\">Email</label>\n";
echo "                <input type=\"email\" id=\"social-email\" name=\"social-email\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <label for=\"social-password\">Senha</label>\n";
echo "                <input type=\"password\" id=\"social-password\" name=\"social-password\" required>\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "                <button type=\"button\" onclick=\"connectSocial()\">Conectar</button>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div id=\"Surpresa\" class=\"tabcontent\">\n";
echo "        <div class=\"container\">\n";
echo "            <h2>Surpresa!</h2>\n";
echo "            <p>Esta é uma área dinâmica e pode ser usada para mostrar conteúdos diferentes.</p>\n";
echo "            <div class=\"form-group\">\n";
echo "                <button type=\"button\" onclick=\"showSurprise()\">Mostrar Surpresa</button>\n";
echo "            </div>\n";
echo "            <div id=\"surprise-content\"></div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div id=\"success-container\" class=\"container\">\n";
echo "        <h2>Bem-vindo, <span id=\"logged-user-name\"></span></h2>\n";
echo "        <button class=\"main-btn\" onclick=\"showMainForm()\">Formulário Principal</button>\n";
echo "        <button class=\"main-btn\" onclick=\"showUserData()\">Dados Salvos</button>\n";
echo "        <button class=\"main-btn\" onclick=\"showFilterData()\">Filtrar e Imprimir</button>\n";
echo "        <button class=\"main-btn\" onclick=\"visualizarPlanilha()\">Salvar Dados do Dia</button>\n";
echo "        <button class=\"main-btn\" onclick=\"visualizarDadosOnline()\">Visualizar Dados Online</button>\n";
echo "    </div>\n";
echo "    <div id=\"success-form\" class=\"container\">\n";
echo "        <h2>Dados do Aluno</h2>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"monitor-nome\">Nome do Monitor</label>\n";
echo "            <input type=\"text\" id=\"monitor-nome\" name=\"monitor-nome\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"xerife-nome\">Nome do Xerife</label>\n";
echo "            <input type=\"text\" id=\"xerife-nome\" name=\"xerife-nome\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"aluno-nome\">Nome do Aluno</label>\n";
echo "            <input type=\"text\" id=\"aluno-nome\" name=\"aluno-nome\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"companhia\">Companhia</label>\n";
echo "            <input type=\"text\" id=\"companhia\" name=\"companhia\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"turma\">Turma</label>\n";
echo "            <input type=\"text\" id=\"turma\" name=\"turma\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"horario-fatos\">Horário dos Fatos</label>\n";
echo "            <input type=\"time\" id=\"horario-fatos\" name=\"horario-fatos\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"fatos-narrados\">Fatos Narrados</label>\n";
echo "            <textarea id=\"fatos-narrados\" name=\"fatos-narrados\" rows=\"4\" required></textarea>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"cpf-aluno\">CPF do Aluno</label>\n";
echo "            <input type=\"text\" id=\"cpf-aluno\" name=\"cpf-aluno\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"tipo-situacao\">Tipo de Situação</label>\n";
echo "            <select id=\"tipo-situacao\" name=\"tipo-situacao\" required>\n";
echo "                <option value=\"gravissima\">Gravíssima</option>\n";
echo "                <option value=\"grave\">Grave</option>\n";
echo "                <option value=\"moderada\">Moderada</option>\n";
echo "                <option value=\"leve\">Leve</option>\n";
echo "            </select>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"data-registrada\">Data Registrada</label>\n";
echo "            <input type=\"date\" id=\"data-registrada\" name=\"data-registrada\" required>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <label for=\"observacao-monitor\">Observação do Monitor</label>\n";
echo "            <textarea id=\"observacao-monitor\" name=\"observacao-monitor\" rows=\"4\" required></textarea>\n";
echo "        </div>\n";
echo "        <div class=\"captcha-container\">\n";
echo "            <input type=\"checkbox\" id=\"captcha\" required>\n";
echo "            <label for=\"captcha\">Não sou um robô</label>\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <button type=\"button\" onclick=\"saveUserData()\">Salvar Dados</button>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div id=\"user-data\" class=\"container\">\n";
echo "        <h2>Dados Salvos</h2>\n";
echo "        <table>\n";
echo "            <thead>\n";
echo "                <tr>\n";
echo "                    <th>ID</th>\n";
echo "                    <th>Nome do Monitor</th>\n";
echo "                    <th>Nome do Xerife</th>\n";
echo "                    <th>Nome do Aluno</th>\n";
echo "                    <th>Companhia</th>\n";
echo "                    <th>Turma</th>\n";
echo "                    <th>Horário dos Fatos</th>\n";
echo "                    <th>Fatos Narrados</th>\n";
echo "                    <th>CPF do Aluno</th>\n";
echo "                    <th>Tipo de Situação</th>\n";
echo "                    <th>Data Registrada</th>\n";
echo "                    <th>Observação do Monitor</th>\n";
echo "                </tr>\n";
echo "            </thead>\n";
echo "            <tbody id=\"user-data-tbody\">\n";
echo "                <!-- Dados dos alunos serão exibidos aqui -->\n";
echo "            </tbody>\n";
echo "        </table>\n";
echo "    </div>\n";
echo "    <div id=\"filter-data\" class=\"container\">\n";
echo "        <h2>Filtrar Dados</h2>\n";
echo "        <div class=\"filter-group\">\n";
echo "            <label for=\"filter-cpf\">CPF do Aluno</label>\n";
echo "            <input type=\"text\" id=\"filter-cpf\" name=\"filter-cpf\">\n";
echo "        </div>\n";
echo "        <div class=\"filter-group\">\n";
echo "            <label for=\"filter-date\">Data</label>\n";
echo "            <input type=\"date\" id=\"filter-date\" name=\"filter-date\">\n";
echo "        </div>\n";
echo "        <div class=\"form-group\">\n";
echo "            <button type=\"button\" onclick=\"filterAndPrint()\">Filtrar e Imprimir</button>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"loader-overlay\" id=\"loader\">\n";
echo "        <div class=\"loader\"></div>\n";
echo "    </div>\n";
echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js\"></script>\n";
echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js\"></script>\n";
echo "    <script>\n";
echo "        const userData = [];\n";
echo "        const googleScriptURL = \'https://script.google.com/macros/s/AKfycbw566x_w5UhunqpU7fh6nf0xhIvE7PpXIjuyYyLRb2a2o6BRYQJ1uT6fsAVdn1OElne/exec\'; // Replace with your Google Apps Script deployment URL\n";
echo "        function toggleForms() {\n";
echo "            var loginForm = document.getElementById(\'login-form\');\n";
echo "            var signupForm = document.getElementById(\'signup-form\');\n";
echo "            if (loginForm.style.display === \'none\') {\n";
echo "                loginForm.style.display = \'block\';\n";
echo "                signupForm.style.display = \'none\';\n";
echo "            } else {\n";
echo "                loginForm.style.display = \'none\';\n";
echo "                signupForm.style.display = \'block\';\n";
echo "            }\n";
echo "        }\n";
echo "        function showLoader() {\n";
echo "            document.getElementById(\'loader\').style.display = \'flex\';\n";
echo "            setTimeout(() => {\n";
echo "                document.getElementById(\'loader\').style.display = \'none\';\n";
echo "                alert(\'Cadastro realizado com sucesso!\');\n";
echo "            }, 3000); // Simulate a 3 second loading time\n";
echo "        }\n";
echo "        function showMainForm() {\n";
echo "            document.getElementById(\'success-form\').style.display = \'flex\';\n";
echo "            document.getElementById(\'user-data\').style.display = \'none\';\n";
echo "            document.getElementById(\'filter-data\').style.display = \'none\';\n";
echo "        }\n";
echo "        function showUserData() {\n";
echo "            document.getElementById(\'success-form\').style.display = \'none\';\n";
echo "            document.getElementById(\'user-data\').style.display = \'flex\';\n";
echo "            document.getElementById(\'filter-data\').style.display = \'none\';\n";
echo "            const tbody = document.getElementById(\'user-data-tbody\');\n";
echo "            tbody.innerHTML = \'\';\n";
echo "            userData.forEach((data, index) => {\n";
echo "                const row = `<tr>\n";
echo "                    <td>${index + 1}</td>\n";
echo "                    <td>${data.monitorNome}</td>\n";
echo "                    <td>${data.xerifeNome}</td>\n";
echo "                    <td>${data.alunoNome}</td>\n";
echo "                    <td>${data.companhia}</td>\n";
echo "                    <td>${data.turma}</td>\n";
echo "                    <td>${data.horarioFatos}</td>\n";
echo "                    <td>${data.fatosNarrados}</td>\n";
echo "                    <td>${data.cpfAluno}</td>\n";
echo "                    <td>${data.tipoSituacao}</td>\n";
echo "                    <td>${data.dataRegistrada}</td>\n";
echo "                    <td>${data.observacaoMonitor}</td>\n";
echo "                </tr>`;\n";
echo "                tbody.innerHTML += row;\n";
echo "            });\n";
echo "        }\n";
echo "        function showFilterData() {\n";
echo "            document.getElementById(\'success-form\').style.display = \'none\';\n";
echo "            document.getElementById(\'user-data\').style.display = \'none\';\n";
echo "            document.getElementById(\'filter-data\').style.display = \'flex\';\n";
echo "        }\n";
echo "        function saveUserData() {\n";
echo "            const monitorNome = document.getElementById(\'monitor-nome\').value;\n";
echo "            const xerifeNome = document.getElementById(\'xerife-nome\').value;\n";
echo "            const alunoNome = document.getElementById(\'aluno-nome\').value;\n";
echo "            const companhia = document.getElementById(\'companhia\').value;\n";
echo "            const turma = document.getElementById(\'turma\').value;\n";
echo "            const horarioFatos = document.getElementById(\'horario-fatos\').value;\n";
echo "            const fatosNarrados = document.getElementById(\'fatos-narrados\').value;\n";
echo "            const cpfAluno = document.getElementById(\'cpf-aluno\').value;\n";
echo "            const tipoSituacao = document.getElementById(\'tipo-situacao\').value;\n";
echo "            const dataRegistrada = document.getElementById(\'data-registrada\').value;\n";
echo "            const observacaoMonitor = document.getElementById(\'observacao-monitor\').value;\n";
echo "            const captcha = document.getElementById(\'captcha\').checked;\n";
echo "            if (!captcha) {\n";
echo "                alert(\"Por favor, verifique a caixa \'Não sou um robô\'.\");\n";
echo "                return;\n";
echo "            }\n";
echo "            const newUserData = {\n";
echo "                monitorNome,\n";
echo "                xerifeNome,\n";
echo "                alunoNome,\n";
echo "                companhia,\n";
echo "                turma,\n";
echo "                horarioFatos,\n";
echo "                fatosNarrados,\n";
echo "                cpfAluno,\n";
echo "                tipoSituacao,\n";
echo "                dataRegistrada,\n";
echo "                observacaoMonitor\n";
echo "            };\n";
echo "            userData.push(newUserData);\n";
echo "            alert(\"Dados salvos com sucesso!\");\n";
echo "            document.getElementById(\'success-form\').reset();\n";
echo "            saveToGoogleSheet(newUserData);\n";
echo "        }\n";
echo "        function saveToGoogleSheet(data) {\n";
echo "            fetch(googleScriptURL, {\n";
echo "                    method: \'POST\',\n";
echo "                    body: JSON.stringify(data),\n";
echo "                    headers: {\n";
echo "                        \'Content-Type\': \'application/json\'\n";
echo "                    }\n";
echo "                })\n";
echo "                .then(response => response.json())\n";
echo "                .then(data => {\n";
echo "                    if (data.status === \'success\') {\n";
echo "                        console.log(\'Dados salvos no Google Sheets com sucesso\');\n";
echo "                    } else {\n";
echo "                        console.error(\'Erro ao salvar dados no Google Sheets\');\n";
echo "                    }\n";
echo "                })\n";
echo "                .catch(error => {\n";
echo "                    console.error(\'Erro:\', error);\n";
echo "                });\n";
echo "        }\n";
echo "        function filterAndPrint() {\n";
echo "            const filterCPF = document.getElementById(\'filter-cpf\').value;\n";
echo "            const filterDate = document.getElementById(\'filter-date\').value;\n";
echo "            const filteredData = userData.filter(data => data.cpfAluno === filterCPF && (!filterDate || data.dataRegistrada === filterDate));\n";
echo "            if (filteredData.length === 0) {\n";
echo "                alert(\"Nenhum dado encontrado para os critérios selecionados.\");\n";
echo "                return;\n";
echo "            }\n";
echo "            const {\n";
echo "                jsPDF\n";
echo "            } = window.jspdf;\n";
echo "            const doc = new jsPDF();\n";
echo "            filteredData.forEach((data, index) => {\n";
echo "                doc.text(`ID: ${index + 1}`, 10, 10);\n";
echo "                doc.text(`Nome do Monitor: ${data.monitorNome}`, 10, 20);\n";
echo "                doc.text(`Nome do Xerife: ${data.xerifeNome}`, 10, 30);\n";
echo "                doc.text(`Nome do Aluno: ${data.alunoNome}`, 10, 40);\n";
echo "                doc.text(`Companhia: ${data.companhia}`, 10, 50);\n";
echo "                doc.text(`Turma: ${data.turma}`, 10, 60);\n";
echo "                doc.text(`Horário dos Fatos: ${data.horarioFatos}`, 10, 70);\n";
echo "                doc.text(`Fatos Narrados: ${data.fatosNarrados}`, 10, 80);\n";
echo "                doc.text(`CPF do Aluno: ${data.cpfAluno}`, 10, 90);\n";
echo "                doc.text(`Tipo de Situação: ${data.tipoSituacao}`, 10, 100);\n";
echo "                doc.text(`Data Registrada: ${data.dataRegistrada}`, 10, 110);\n";
echo "                doc.text(`Observação do Monitor: ${data.observacaoMonitor}`, 10, 120);\n";
echo "                if (index < filteredData.length - 1) {\n";
echo "                    doc.addPage();\n";
echo "                }\n";
echo "            });\n";
echo "            doc.save(\'dados_filtrados.pdf\');\n";
echo "        }\n";
echo "        function saveToExcel() {\n";
echo "            const worksheet = XLSX.utils.json_to_sheet(userData);\n";
echo "            const workbook = XLSX.utils.book_new();\n";
echo "            XLSX.utils.book_append_sheet(workbook, worksheet, \"Dados\");\n";
echo "            XLSX.writeFile(workbook, \'dados_alunos.xlsx\');\n";
echo "        }\n";
echo "        function visualizarPlanilha() {\n";
echo "            const workbook = XLSX.utils.book_new();\n";
echo "            const worksheet = XLSX.utils.json_to_sheet(userData);\n";
echo "            XLSX.utils.book_append_sheet(workbook, worksheet, \"Dados\");\n";
echo "            const wbout = XLSX.write(workbook, {\n";
echo "                bookType: \'xlsx\',\n";
echo "                type: \'binary\'\n";
echo "            });\n";
echo "            const blob = new Blob([s2ab(wbout)], {\n";
echo "                type: \'application/octet-stream\'\n";
echo "            });\n";
echo "            const url = window.URL.createObjectURL(blob);\n";
echo "            const a = document.createElement(\'a\');\n";
echo "            a.href = url;\n";
echo "            a.download = \'dados_alunos.xlsx\';\n";
echo "            a.click();\n";
echo "            window.URL.revokeObjectURL(url);\n";
echo "        }\n";
echo "        function visualizarDadosOnline() {\n";
echo "            window.open(\'https://docs.google.com/spreadsheets/d/1QhkgEbRtwrudyfFS3u3vV5T1xtohs0RL_vSCCfwaFvo/edit?gid=0#gid=0\', \'_blank\');\n";
echo "        }\n";
echo "        function s2ab(s) {\n";
echo "            const buf = new ArrayBuffer(s.length);\n";
echo "            const view = new Uint8Array(buf);\n";
echo "            for (let i = 0; i < s.length; i++) {\n";
echo "                view[i] = s.charCodeAt(i) & 0xFF;\n";
echo "            }\n";
echo "            return buf;\n";
echo "        }\n";
echo "        function logout() {\n";
echo "            document.getElementById(\'login-form\').style.display = \'block\';\n";
echo "            document.getElementById(\'success-container\').style.display = \'none\';\n";
echo "            document.getElementById(\'success-form\').style.display = \'none\';\n";
echo "            document.getElementById(\'user-data\').style.display = \'none\';\n";
echo "            document.getElementById(\'filter-data\').style.display = \'none\';\n";
echo "        }\n";
echo "        function openTab(evt, tabName) {\n";
echo "            var i, tabcontent, tablinks;\n";
echo "            tabcontent = document.getElementsByClassName(\"tabcontent\");\n";
echo "            for (i = 0; i < tabcontent.length; i++) {\n";
echo "                tabcontent[i].style.display = \"none\";\n";
echo "            }\n";
echo "            tablinks = document.getElementsByClassName(\"tablinks\");\n";
echo "            for (i = 0; i < tablinks.length; i++) {\n";
echo "                tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\n";
echo "            }\n";
echo "            document.getElementById(tabName).style.display = \"block\";\n";
echo "            evt.currentTarget.className += \" active\";\n";
echo "        }\n";
echo "        function resetUser() {\n";
echo "            alert(\"Usuário resetado com sucesso!\");\n";
echo "        }\n";
echo "        function connectSocial() {\n";
echo "            alert(\"Conectado às redes sociais!\");\n";
echo "        }\n";
echo "        function showSurprise() {\n";
echo "            const surpriseContent = document.getElementById(\'surprise-content\');\n";
echo "            surpriseContent.innerHTML = \"<p>Você encontrou a surpresa! Aproveite o seu dia!</p>\";\n";
echo "        }\n";
echo "    </script>\n";
echo "</body>\n";
echo "</html>\n";
?>